import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bitcoin Guesser",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1>Bitcoin Guesser</h1>
          <section aria-label="Score">
      			<h2>Score:</h2>
            <p>0</p>
		      </section>
        </header>
        {children}
      </body>
    </html>
  );
}
