import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Refresher } from "./Refresher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bitcoin Guesser",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Refresher />
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
