name: CI/CD
on:
  push:
    branches: [main]

concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  TheJob:
    runs-on: ubuntu-latest
    env:
      CI: true
      COINCAP_API_KEY: ${{ secrets.COINCAP_API_KEY }}
    steps:
      # Prepare
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{vars.AWS_ACCOUNT_ID}}:role/GitHub
          role-duration-seconds: 900 #adjust as needed for your build time
          aws-region: eu-west-1
      # CI
      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      - if: steps.playwright-cache.outputs.cache-hit != 'true'
        name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Store Playwright tests artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      # CD
      - run: npm run deploy:prod
