name: CI/CD
on:
  push:
    branches: [main]

concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  TheJob:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      # Prepare
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{vars.AWS_ACCOUNT_ID}}:role/GitHub
          role-duration-seconds: 900 #adjust as needed for your build time
          aws-region: eu-west-1
      # CI
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm exec playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      # CD
      - run: pnpm run deploy:prod
